### PR TITLE
Add `sdlToSchema` to public API

### PR DESCRIPTION
**Pull request by bollwyvl**
Thanks for this tool!

Motivated by https://github.com/graphql-kit/graphql-voyager/issues/238#issuecomment-1588570268, this strawman exports `sdlToIntrospection`. 

A concrete use case for this is when a live server is not readily accessible, but an SDL is available.

A more sweeping approach would be to also ship an intermediate `lib` such that a downstream could:

```ts
import { sdlToIntrospection } from 'graphql-voyager/lib/utils/sdl-to-introspection';
```

### CODE REVIEW

**Comment by LunaticMuch** [comment]
@bollwyvl you need to rebase. In version 2.0 the function is now `sdlToSchema`

**Review by LunaticMuch — CHANGES_REQUESTED** [review]
Rebase required

**Comment by bollwyvl** [comment]
@LunaticMuch thoughts?

**Comment by optimistex** [comment]
@LunaticMuch Current changes are correct. Can you please merge it?
@bollwyvl FYI

**Review by LunaticMuch — APPROVED** [review]

**Comment by bollwyvl** [comment]
Hey, thanks a lot!

**Pull request merged**
